### ISSUE TITLE
Carla simulator version 0.9.X

### ISSUE THREAD

**Issue by sjames** [jerry73204/carla-rust#1]
Hi @jerry73204 

This is a great project and I was just trying this out to connect to the latest version of the simulator I installed on Ubuntu.

WARNING: Version mismatch detected: You are trying to connect to a simulator that might be incompatible with this API 
WARNING: Client API version     = 0.4.0-1-gb3fbf09-dirty 
WARNING: Simulator API version  = 0.9.13 

I see that the Client API is quite old.  What would it take to move to a newer version?  Is this something I can help with?  

Regards,
Sojan

**Comment by jerry73204** [comment]
@sjames Thanks for your attention. It was actually based on patched 0.9.13 source code (see [here](https://github.com/jerry73204/carla-rust/blob/master/carla-src/default_config.json5)). I guess the weird version was generated by `git describe` picking the old 0.4.0 tag, at least the commit hash `gb3fbf09` is correct to me. This crate should work on Ubuntu 20.04 out of the box.

**Comment by sjames** [comment]
OK great to know that!  Out of curiosity, what is the patch you need to apply on the source code?

**Comment by jerry73204** [comment]
The build script was changed to use clang-8. Unpached carla build script calls `clang`, which version is 10 on Ubuntu 20.04, and it failed for that reason. Carla compilation asks you to replace clang on system but I may not have that permission, and thus the patch.

**Comment by jerry73204** [comment]
Close it given that I think the explanation is clear.
