### ISSUE TITLE
Small typo in build.rs rerun-if-env-changed

### ISSUE THREAD

**Issue by badicsalex** [jerry73204/carla-rust#4]
Hi,

I've been casually looking at the code and stumbled into this (somewhat unimportant) typo:

https://github.com/jerry73204/carla-rust/blob/34fe9f3953aa9547e65d9943eed8e9feefb3ab18/carla-sys/build.rs#LL11C28-L11C28

I guess it should be `CARLA_DIR`

**Comment by jerry73204** [comment]
It annoyed me that the local build keeps recompiling and you got it. It is fixed in recent releases.
