### ISSUE TITLE
Issue when install on ubuntu 22 

### ISSUE THREAD

**Issue by trand2k** [jerry73204/carla-rust#6]
Hi author,
I have thí bug when cargo build this repo, can you help me? 
![Screenshot from 2023-11-14 09-01-50](https://github.com/jerry73204/carla-rust/assets/53207542/0c799836-beec-4ae0-9baa-24e098cd4e51)
Thank you,

**Comment by jerry73204** [comment]
Ubuntu 22.04 ships newer clang not working with current clang-sys. Please try the troubleshooting section and see if it works for you.
https://github.com/jerry73204/carla-rust#build-failed-with-clang--14

**Comment by trand2k** [comment]
> Ubuntu 22.04 ships newer clang not working with current clang-sys. Please try the troubleshooting section and see if it works for you. https://github.com/jerry73204/carla-rust#build-failed-with-clang--14

i will remove clang and update , but it have same bug

**Comment by jerry73204** [comment]
Perhaps you have to install the C++ headers for that clang version directly. Try the other versions (11, 10, etc) as well. 

```sh
sudo apt install libstdc++-12-dev
```

**Comment by trand2k** [comment]
![Screenshot from 2023-11-14 10-28-56](https://github.com/jerry73204/carla-rust/assets/53207542/20ed4eb8-1498-488a-81ef-94fba0c044bf)
this bug appear when i use clang lower version 
![Screenshot from 2023-11-14 10-29-49](https://github.com/jerry73204/carla-rust/assets/53207542/f049bc0c-8c92-4ad1-a296-e5caa973535b)

**Comment by jerry73204** [comment]
It's using the wrong version clang from your error message. Note that all env vars in the troubleshooting section must be set. Changing the PATH to clang-12 is not enough. I tried the instructions again on my Ubuntu 22.04 box and it worked for me.

**Comment by trand2k** [comment]
> It's using the wrong version clang from your error message. Note that all env vars in the troubleshooting section must be set. Changing the PATH to clang-12 is not enough. I tried the instructions again on my Ubuntu 22.04 box and it worked for me.

it work , thank you for your support
